# Generated by Django 5.2.4 on 2025-08-05 07:12

from django.db import migrations, models

def create_variation_categories(apps, schema_editor):
    VariationCategory = apps.get_model('store', 'VariationCategory')
    
    # Create default variation categories
    default_categories = [
        {'name': 'color', 'display_name': 'Color'},
        {'name': 'size', 'display_name': 'Size'},
        {'name': 'ssd', 'display_name': 'SSD'},
        {'name': 'ram', 'display_name': 'RAM'},
    ]
    
    for category_data in default_categories:
        VariationCategory.objects.get_or_create(
            name=category_data['name'],
            defaults={
                'display_name': category_data['display_name'],
                'is_active': True
            }
        )

def reverse_variation_categories(apps, schema_editor):
    VariationCategory = apps.get_model('store', 'VariationCategory')
    VariationCategory.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_id_alter_variation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name (e.g., 'color', 'size')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Display name (e.g., 'Color', 'Size')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Variation Category',
                'verbose_name_plural': 'Variation Categories',
                'ordering': ['display_name'],
            },
        ),
        migrations.RunPython(create_variation_categories, reverse_variation_categories),
    ]
