# Generated by Django 5.2.4 on 2025-08-05 07:12

from django.db import migrations, models
import django.db.models.deletion

def convert_variation_categories(apps, schema_editor):
    Variation = apps.get_model('store', 'Variation')
    VariationCategory = apps.get_model('store', 'VariationCategory')
    
    # Create a temporary field to store the foreign key
    for variation in Variation.objects.all():
        try:
            # Get the category by name
            category = VariationCategory.objects.get(name=variation.variation_category)
            # Update the variation to use the foreign key
            variation.variation_category_new = category
            variation.save()
        except VariationCategory.DoesNotExist:
            # If category doesn't exist, create it
            category = VariationCategory.objects.create(
                name=variation.variation_category,
                display_name=variation.variation_category.title(),
                is_active=True
            )
            variation.variation_category_new = category
            variation.save()

def reverse_convert_variation_categories(apps, schema_editor):
    # This is a complex reverse operation, so we'll just pass
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_create_variation_category_only'),
    ]

    operations = [
        # First, add a new foreign key field
        migrations.AddField(
            model_name='variation',
            name='variation_category_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variationcategory'),
        ),
        # Convert the data
        migrations.RunPython(convert_variation_categories, reverse_convert_variation_categories),
        # Remove the old field
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
        # Rename the new field to the original name
        migrations.RenameField(
            model_name='variation',
            old_name='variation_category_new',
            new_name='variation_category',
        ),
        # Make the field non-nullable
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variationcategory'),
        ),
        # Add unique constraint
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation_category', 'variation_value')},
        ),
    ]
