# Generated by Django 5.2.7 on 2026-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_account_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_verification', 'Pending Verification'), ('paid', 'Paid'), ('failed', 'Failed')], default='unpaid', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_account_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash')], default='cod', max_length=20),
        ),
    ]
